<h1><i class="fas fa-cogs"></i> Administration</h1>

<form method="POST" action="addArticle.php">
    <fieldset>
        <legend><i class="fas fa-newspaper"></i> Ajouter un article</legend>

        <label for="title">Titre :</label>
        <input id="title" type="text" name="title">

        <label for="content">Contenu de l'article :</label>
        <textarea id="content" name="content"></textarea>
        
        <select name="idCategory" size="1">
            <?php foreach ($categories as $category) { ?>
            <option value="<?php echo $category['id']; ?>"><?php echo htmlspecialchars($category['label']); ?></option>
            <?php } ?>
        </select>
        
        <select name="idAuthor" size="1">
            <?php foreach ($authors as $author) { ?>
            <option value="<?php echo $author['id']; ?>"><?php echo htmlspecialchars($author['name']); ?></option>
            <?php } ?>
        </select>
        
        <div>
            <input type="submit" id="save-comment" value="Ajouter">
            <input type="reset" id="reset-form" value="Annuler">
        </div>

    </fieldset>

</form>