<h1><i class="fas fa-home"></i> Accueil</h1>

<ul class="articleList">
    <?php foreach ($allArticles as $article) { ?>
        <li><h2><a href="showArticle.php?idArticle=<?php echo $article['id']; ?>">
                    <?php echo htmlspecialchars($article['title']); ?></a>
            </h2>
            <article>
                <?php
                if ($allArticles) {
                    if (strlen($article['content']) > 50) {
                        echo ($content = substr(htmlspecialchars($article['content']), 0, strpos($article['content'], " ", 50)) . " [...]");
                    } else {
                        echo htmlspecialchars($article['content']);
                    }
                } else {
                    echo "Pas encore d'article :/";
                }
                ?></article>
            <small><?php echo "Rédigé par " . htmlspecialchars($article['name']) . " le " . htmlspecialchars(substr($article['creationDate'], 0, 10)); ?></small>
        </li>
    <?php } ?>
</ul>