<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <!-- En-tête commune de l'application -->
    <header>
        <nav>
            <a id="title" href="php/index.php"><i class="fas fa-microphone"></i> Blog de la mort qui tue !</a>
            <a href="#"><i class="fas fa-cogs"></i> Administration</a>
        </nav>
        
    </header>

    <main class="container">
        <h1><i class="fas fa-home"></i> Accueil</h1>
        <div>
            
        </div>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="container">
        <small>Le blog des élèves de la 3W Academy</small>
    </footer>
</body>
</html>